# set a specific start time if desired
# start_time: "2015-02-24T18:19:39.12Z"

# logging - set to 0 to disable
# verbose: 1

num_workers: 1

# simulation speed - set to 0 to run the simulator as fast as possible
# sim_interval: 500ms

# maximum number of packages to simulate at any point (0 = unlimited)
max_packages: 10000

# exit after delivering this many packages (0 = unlimited)
# max_delivered: 1

# number of packages to generate per tick
packages_per_tick:
  avg: 10000
  stddev: 300

# how long packages should take to be processed
hours_at_rest:
  avg: 3
  stddev: 2

# probability a package is shipped "express"
probability_express: 0.4

# only care about shipping packages at least this far
min_shipping_distance_km: 1000

# air freight is pricy - make sure a segment is far enough
min_air_freight_distance_km: 2000

# average land speed
avg_land_speed_kmph: 50

# average air speed
avg_air_speed_kmph: 750

database:
  host: s2-agg-0
  port: 3306
  username: root
  password: root
  database: logistics

topics:
  compression: false
  batch_max_bytes: 65535   # 64 * 1024
  brokers:
    - rp-node-0:9092

metrics:
  port: 9000
