version: '3.8'
services:
  redpanda:
    image: vectorized/redpanda:v21.6.1
    container_name: rp-node-0
    entrypoint:
      - /usr/bin/rpk
      - redpanda
      - start
      - --smp=2
      - --memory=4G
      - --overprovisioned
      - --default-log-level=info
      - --node-id=0
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,DOCKER://redpanda:9092,OUTSIDE://redpanda:9093
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,DOCKER://redpanda:9092,OUTSIDE://127.0.0.1:9093
    ports:
      - 9092:9092
      - 9093:9093
      - 29092:29092
    volumes:
      - /var/lib/redpanda/data
  redpanda-setup:
    container_name: rp-setup
    image: vectorized/redpanda:v21.6.1
    entrypoint: /bin/bash -c
    command:
      - |
        rpk --brokers rp-node-0:9092 topic create --partitions 8 transitions
        rpk --brokers rp-node-0:9092 topic create --partitions 8 packages
  singlestore:
    image: singlestore/cluster-in-a-box:centos-7.3.11-f7c82b8166-3.2.9-1.11.5
    container_name: s2-agg-0
    volumes:
      # persist data between runs:
      - /var/lib/memsql
      - ./schema.sql:/init.sql:ro
      - ./data:/data:ro
      - ./data/metrics/singlestore_exporter.cnf:/etc/memsql/memsql_exporter.cnf:ro
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      - ROOT_PASSWORD=root
      - LICENSE_KEY=${SINGLESTORE_LICENSE}
      - START_AFTER_INIT=Y
  simulator:
    build: simulator
    image: singlestore-logistics-simulator
    container_name: simulator
    environment:
      - SIMULATOR_ID=local
  prometheus:
    image: prom/prometheus:v2.27.1
    container_name: prometheus
    volumes:
      - ./data/metrics/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    environment:
      - GF_USERS_DEFAULT_THEME=light
      - GF_SECURITY_ADMIN_USER=root
      - GF_SECURITY_ADMIN_PASSWORD=root
      - "GF_INSTALL_PLUGINS=grafana-worldmap-panel,https://github.com/WilliamVenner/grafana-timepicker-buttons/releases/download/v4.1.1/williamvenner-timepickerbuttons-panel-4.1.1.zip;grafana-timepicker-buttons"
    volumes:
      - /var/lib/grafana
      - ./data/metrics/dashboards:/dashboards:ro
      - ./data/metrics/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/all.yaml:ro
      - ./data/metrics/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/all.yaml:ro
    ports:
      - 3000:3000